In [1]:
import pandas as pd
df = pd.read_csv('sbux.csv')

In [2]:
df[0,0]

KeyError: (0, 0)

In [3]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [4]:
df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'name']

In [5]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'name'], dtype='object')

In [6]:
df['open']

0       27.920
1       28.260
2       28.000
3       28.230
4       27.765
         ...  
1254    56.280
1255    55.900
1256    55.530
1257    53.685
1258    55.080
Name: open, Length: 1259, dtype: float64

In [7]:
df[['open','close']]

open   close
0     27.920  28.185
1     28.260  28.070
2     28.000  28.130
3     28.230  27.915
4     27.765  27.775
...      ...     ...
1254  56.280  56.000
1255  55.900  55.770
1256  55.530  54.690
1257  53.685  55.610
1258  55.080  54.460

[1259 rows x 2 columns]

In [10]:
type(df['open'])

pandas.core.series.Series

In [11]:
type(df[['open','close']])

pandas.core.frame.DataFrame

In [ ]:
# IMPORTANT
# square brackets [] in Python List or numpy array retrieves - ROWS
# square brackets [] - returns COLUMNS

In [12]:
df.iloc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
name            SBUX
Name: 0, dtype: object

In [13]:
df.loc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
name            SBUX
Name: 0, dtype: object

In [ ]:
# iloc - for integer indices
# loc - for index label

In [14]:
df2 = pd.read_csv('sbux.csv', index_col='date')

In [15]:
df2.head()

open    high     low   close   volume  Name
date                                                     
2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [16]:
df2.loc['2013-02-08']

open        27.92
high       28.325
low         27.92
close      28.185
volume    7146296
Name         SBUX
Name: 2013-02-08, dtype: object

In [17]:
type(df2.loc['2013-02-08'])

pandas.core.series.Series

In [18]:
df[df['open'] > 64]

date   open    high    low  close   volume  name
1087  2017-06-05  64.85  64.870  64.18  64.27  6809284  SBUX
1088  2017-06-06  64.22  64.350  64.05  64.16  5448439  SBUX
1089  2017-06-07  64.13  64.295  63.34  63.50  8364994  SBUX

In [19]:
df[df['name'] != 'SBUX']

Empty DataFrame
Columns: [date, open, high, low, close, volume, name]
Index: []

In [20]:
type(df[df['name'] != 'SBUX'])

pandas.core.frame.DataFrame

In [22]:
import numpy as np
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
A[A%2 == 0]

array([0, 2, 4, 6, 8])

In [24]:
type(A[A%2 == 0])

numpy.ndarray

In [25]:
# Convert dataframe into numpy arrays

df.values

array([['2013-02-08', 27.92, 28.325, ..., 28.185, 7146296, 'SBUX'],
       ['2013-02-11', 28.26, 28.26, ..., 28.07, 5457354, 'SBUX'],
       ['2013-02-12', 28.0, 28.275, ..., 28.13, 8665592, 'SBUX'],
       ...,
       ['2018-02-05', 55.53, 56.26, ..., 54.69, 16059955, 'SBUX'],
       ['2018-02-06', 53.685, 56.06, ..., 55.61, 17415065, 'SBUX'],
       ['2018-02-07', 55.08, 55.43, ..., 54.46, 13927022, 'SBUX']],
      dtype=object)

In [26]:
type(df.values)

numpy.ndarray

In [28]:
A = df[['open','close']].values
A

array([[27.92 , 28.185],
       [28.26 , 28.07 ],
       [28.   , 28.13 ],
       ...,
       [55.53 , 54.69 ],
       [53.685, 55.61 ],
       [55.08 , 54.46 ]])

In [29]:
type(df[['open','close']].values)

numpy.ndarray

In [32]:
smalldf = df[['open','close']]
smalldf.to_csv('output.csv')

In [34]:
# this has an additional index column
!head output.csv

,open,close
0,27.92,28.185
1,28.26,28.07
2,28.0,28.13
3,28.23,27.915
4,27.765,27.775
5,27.805,27.17
6,27.18,27.225
7,27.3,26.655
8,26.535,26.675


In [35]:
smalldf.to_csv('output.csv', index=False)
!head output.csv

open,close
27.92,28.185
28.26,28.07
28.0,28.13
28.23,27.915
27.765,27.775
27.805,27.17
27.18,27.225
27.3,26.655
26.535,26.675
