In [1]:
import numpy as np

# genrating Data

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [4]:
# avoid to conflict with var i (identity)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# random data
np.random.random()

0.11287701737853484

In [7]:
np.random.random((2,3))

array([[0.08430836, 0.28632405, 0.64188703],
       [0.31818475, 0.32285374, 0.61884261]])

In [10]:
# from different distribution [uniform] or [normal]

np.random.randn(2,3)

array([[ 0.08215089,  0.44088588, -0.13626894],
       [ 0.09083   ,  0.76134716,  0.00932192]])

In [12]:
R = np.random.randn(10000)
R.mean()

-0.005057031256083502

In [18]:
np.mean(R)

0.01007473534967797

In [14]:
R.var()

0.9977915039655391

In [15]:
R.std()

0.9988951416267571

In [19]:
R = np.random.randn(10000,3)
R.mean(axis=0)

array([ 0.0083977 ,  0.00148003, -0.00484994])

In [20]:
R.mean(axis=1)

array([-0.18970428,  0.36579499, -0.34179464, ...,  0.7799533 ,
       -0.05371051, -0.66306678])

In [22]:
R.mean(axis=1).shape

(10000,)

In [23]:
np.cov(R)

array([[ 0.29754966,  0.13298654,  0.35773523, ...,  0.05078947,
         0.43093365, -0.32528437],
       [ 0.13298654,  0.05991172,  0.17120284, ...,  0.00602925,
         0.1619349 , -0.13336968],
       [ 0.35773523,  0.17120284,  0.69981483, ..., -0.33624922,
        -0.21277276, -0.10478184],
       ...,
       [ 0.05078947,  0.00602925, -0.33624922, ...,  0.59393047,
         1.15016902, -0.47725544],
       [ 0.43093365,  0.1619349 , -0.21277276, ...,  1.15016902,
         2.60458232, -1.24689429],
       [-0.32528437, -0.13336968, -0.10478184, ..., -0.47725544,
        -1.24689429,  0.65949899]])

In [24]:
np.cov(R).shape

(10000, 10000)

In [25]:
np.cov(R.T)

array([[ 1.00237240e+00, -2.68808361e-04, -1.29679496e-02],
       [-2.68808361e-04,  1.01246578e+00, -8.90755424e-03],
       [-1.29679496e-02, -8.90755424e-03,  1.01355198e+00]])

In [26]:
np.cov(R, rowvar=False)

array([[ 1.00237240e+00, -2.68808361e-04, -1.29679496e-02],
       [-2.68808361e-04,  1.01246578e+00, -8.90755424e-03],
       [-1.29679496e-02, -8.90755424e-03,  1.01355198e+00]])

In [27]:
np.random.randint(0,10,size=(3,3))

array([[7, 4, 2],
       [8, 8, 4],
       [4, 1, 1]])

In [29]:
np.random.choice(10, size=(3,3))

array([[4, 2, 0],
       [3, 2, 2],
       [7, 7, 7]])