In [1]:
import numpy as np

Python List

In [2]:
pl = [1,2,3]
pl

[1, 2, 3]

In [3]:
for i in pl:
    print(i)

1
2
3


Numpy Array

In [4]:
na = np.array([2,2,3])
na

array([2, 2, 3])

In [5]:
type(na)

numpy.ndarray

In [6]:
print(pl == na)

[False  True  True]


Adding Python List

In [7]:
pl = pl + [4]
type(pl)

list

In [8]:
pl.append(5)
pl

[1, 2, 3, 4, 5]

In [9]:
# Attempting to append to a numpy array
#! na.append(6)

# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# Cell In[9], line 1
# ----> 1 na.append(6)
# 
# AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
type(na)

numpy.ndarray

Attempting to add numpy array [! array is of fixed size]

In [11]:
na + np.array([10])

array([12, 12, 13])

In [12]:
na = na + [10]
na

array([12, 12, 13])

The above ouput is result of "Broadcasting"

In [13]:
#! na = na + [10,2]

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[12], line 1
# ----> 1 na = na + [10,2]
#
# ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [14]:
na = na + [10,20,30]
na

array([22, 32, 43])

In [15]:
ml = [1,2,3]
# multiplication of list | Output: Repeat List
ml = 2 * ml
ml

[1, 2, 3, 1, 2, 3]

In [16]:
na = np.array([1,2,3])
# Numpy array multiplcation
na = 2 * na
na

array([2, 4, 6])

In [17]:
# List comprehension
pl = [1,2,3]
pl = [ e * 10 for e in pl]
pl

[10, 20, 30]

In [18]:
# PowerOf using list
pl = [1,2,3]
pl = [ e**3 for e in pl]
pl

[1, 8, 27]

In [31]:
# PowerOf using Munpy
na = np.array([1,2,3])
na = na**2
na

array([1, 4, 9])

In [29]:
# math functions on Mumpy array
print(np.sqrt(na))
print(np.log(na))

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
